### ISSUE TITLE
IDS-DRR | Curate a list of variables and data sources used in the current model

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/IDS-DRR-Data-Sources#1]
For each variable, we need:
1. variable_title
2. variable_type (user-defined)
3. data_source_title
4. data_source_url
5. update_frequency
6. data_sourcing_methodology (manual/scraping/API/procuring-it)
7. data_sourcing_script
8. data_transformation_script
9. type_of_values (numeric/categorical/other)
10. variable_documentation (sourcing and transformation)
11. last_update_date
12. from_date
13. to_date

**Comment by apoorv74** [comment]
- All scripts in place by July 14th
- Target to deploy and test the data pipeline by July 21st

**Comment by d-saikrishna** [comment]
Here is the pipeline audit I created for all the variables that are used in the final SEM Model as of now:

https://docs.google.com/spreadsheets/d/1RRW5KZ1Csb3TPBgz_SZrtNSX3pT_W7upUE2wkHAoZOA/edit#gid=0

We should update this as and when more variables are used in the SEM Model.

Requesting @shreyaagrawal0809 to add scraper details on Assam tenders.

**Comment by apoorv74** [comment]
@d-saikrishna - Please move the sheet to the shared project drive.
