### ISSUE TITLE
IDS-DRR IMD Source Pipeline

### ISSUE THREAD

**Issue by d-saikrishna** [CivicDataLab/IDS-DRR-Data-Sources#11]
@tauseefsshah 
We have to write script(s):
1. To extract `Rainfall` data from IMD (Indian Meteorological Department)
2. Aggregate (**mean**) rainfall for each revenue circle in Assam - on a monthly basis

Resources:
1. [imdlib](https://pypi.org/project/imdlib/) is a Python Package useful for downloading IMD data. [Documentation](https://imdlib.readthedocs.io/en/latest/)
2. [Assam Revenue circle maps](https://github.com/CivicDataLab/IDS-DRR-Data-Pipeline/blob/main/Maps/Assam_Revenue_Circles/assam_revenue_circle_nov2022.geojson) -- This is the map we have to use to aggregate IMD data at Revenue circle level.

Additional references:
1. [Tutorial on using imdlib](https://www.youtube.com/watch?v=uSIPPY5WRaM) - You can find many other tutorials.
2. [Zonal Statisitics](https://www.youtube.com/watch?v=VIr-pejky6E&t=1317s) - is the keyword you have to lookup on to aggregate IMD data in a revenue circle.

**Comment by d-saikrishna** [comment]
@tauseefsshah to solve where you got stuck:

1. Each tif file you downloaded from IMDLIB will have multiple bands. (Consider band = array). Each band/array for one date. So When you download tif for a month, you get 30/31 bands/arrays.
2. Now you have to take a mean of all 30/31 bands/arrays and create a single array. That is the array of mean rainfall in a month. You can get some idea of doing this from this [code](https://github.com/CivicDataLab/IDS-DRR-Data-Pipeline/blob/main/Sources/BHUVAN/scripts/transformer.py).  `raster.read(1)` Opens only one band/array - You have to loop across bands/arrays and take mean. 
3. It is this mean array that you have to send to the zonal_stats function.

Let me know if you get stuck again.

**Comment by tauseefsshah** [comment]
@d-saikrishna Still doesn't work. I have [updated the code](https://github.com/CivicDataLab/IDS-DRR-Data-Pipeline/commit/1fd738b58fbaff03663472329b61fc2095234635) to have the average rainfall per month and saving that as `tif` but when I read it, it's still showing `ValueError: negative dimensions are not allowed`. When I check the `tif` in qgis, it looks good.
![image](https://github.com/CivicDataLab/IDS-DRR-Data-Pipeline/assets/63847553/b75930c2-7c81-4ef0-b333-fd9cf4a17db8)
![image](https://github.com/CivicDataLab/IDS-DRR-Data-Pipeline/assets/63847553/6c439d1b-a5b4-44d8-95ea-249adf8db382)

**Comment by d-saikrishna** [comment]
Interesting issues that we can propose:

1. imdlib package (which serves IMD data through Python) is using a bad standard to serve the rasters. The rasters are good for visualisation - but fail when we want to calculate zonal statistics out of it. We fixed it. We can propose this as an issue or write a blog about it.
2. While calculating zonal stats, raster stats package is not taking a weighted average of pixels. As a result, it might miss a lot of pixels that are on the borders of a polygon (a problem especially if the pixel size is high). We solved it through resampling rasters to lesser spatial resolution. But if we can develop a way to take weighted average based on overlap %- that will be very useful

**Comment by d-saikrishna** [comment]
@tauseefsshah 

Once you are done with the scripts, create a small ETL diagram that we use in the README section. You can refer to the diagrams used in SENTINEL, BHUVAN etc. 

You can create a duplicate slide in the following Presentation and download the image in the `docs` folder within IMD folder.
https://docs.google.com/presentation/d/1YQ4t21dduS18D9CLj6zddQ5v9KdEenzoqPSaZu2BhRo/edit#slide=id.g27c4711d02d_0_0

Feel free to detail things out in the README section :)

**Comment by d-saikrishna** [comment]
@tauseefsshah I have merged the code and made a few changes to suit the file naming convention. Every thing worked fine except for one issue.

The code is breaking when I run for 2023 year. Please check that once.

**Comment by d-saikrishna** [comment]
@tauseefsshah could you check it for 2023 year once?

**Comment by d-saikrishna** [comment]
Data is not available for 2023 yet. Source: [Link](https://imdpune.gov.in/cmpg/Griddata/Rainfall_25_NetCDF.html)

**Comment by d-saikrishna** [comment]
https://imdpune.gov.in/cmpg/Realtimedata/Rainfall/Rain_Download.html# -- for realtime data - need a way to integrate this

**Comment by d-saikrishna** [comment]
Data for 2023 is now available ad added
