### ISSUE TITLE
IDS-DRR Data Pillar Documentations - README, Presentations, etc.

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/IDS-DRR-Data-Sources#2]
The current README is written for IDEA-FRM. We need to add details about IDS-DRR and what is the objective of this repo. 

@d-saikrishna - Please keep this repo updated.

**Comment by d-saikrishna** [comment]
I'm creating a diagram template for each Data Source in the IDS-DRR Pipeline. [Link](https://docs.google.com/presentation/d/1YQ4t21dduS18D9CLj6zddQ5v9KdEenzoqPSaZu2BhRo/edit#slide=id.g25d404a8aed_0_66)

Added these diagrams in the README of respective Sources.

**Comment by d-saikrishna** [comment]
Using this space to track any documentation related issues for IDS-DRR -- including my IndiaFOSS presentation

**Comment by d-saikrishna** [comment]
Data sources methodology document -- for ASDMA MOU Annexure

https://docs.google.com/document/d/1qL40YwyoKoRfS5xb9ISisjC06IpeqnB9hKdW-7afpU8/edit

**Comment by d-saikrishna** [comment]
IDS-DRR Data pillar Documentation checklist:

- [ ] IndiaFOSS3.0 Presentation
- [ ] Indicator Master file
- [ ] Metadata Organization
- [ ] Metadata Datasets

**Comment by apoorv74** [comment]
For metadata Organisation, can we share the table we added in the technical annexure.

**Comment by d-saikrishna** [comment]
Use these presentations:
1. https://docs.google.com/presentation/d/1eaQwe93uMFDWsrbqYRaa3x9b5T5P9EiqQcMGSZeRDz0/edit#slide=id.g2456a16d657_0_0
2. https://docs.google.com/presentation/d/16y3ZK6VcYFbNjOp9j9O71QSGf9zatJvshXjuIL5Jh4c/edit#slide=id.g12a7c9c537b_0_1862

**Comment by d-saikrishna** [comment]
Data Dictionary created

**Comment by d-saikrishna** [comment]
Latest update/tasks after the MVP presentation:

- [ ] Taxonomy is going to change. Data Dictionary should be changed accordingly.
- [ ] Work on Model Documentation (Blogs, PPTs etc) -- has to be discussed during the checkin.

**Comment by d-saikrishna** [comment]
Model Presentation - [Link](https://docs.google.com/presentation/d/1GFJohybDxMeR9EsL1jbv-zmHwSHUrThSks8QHb7i7Qo/edit#slide=id.p)

**Comment by d-saikrishna** [comment]
- [ ] [New Model](https://drive.google.com/drive/u/1/folders/1TZL17kAeVY1EygvW4_cqLhjXF2clNl3e?q=sharedwith:saikrishna%40civicdatalab.in%20parent:1TZL17kAeVY1EygvW4_cqLhjXF2clNl3e) - Has to be reviewed and automated

**Comment by d-saikrishna** [comment]
Data Dictionary updates:

- [ ] indicatorDescription should be < 150 characters.


**Few questions we need clarity on:**
1. Are we working on the district level layer on front-end? (Note that the variables are not at district level - we can only provide factor scores at district level if needed) Ruthvik Mandapati Aparna
2. Are we showing variables on the analytics page? Or are we redirecting the user to data listing page for variables? If we are showing the variables on analytics page, what all variables do we want to show for each factor? Rakhi Aparna Ruthvik Mandapati

**Comment by d-saikrishna** [comment]
Tracking all Model related documentation here

There are four factors - I should document for each factor score calculation

- [ ] Flood Hazard
- [ ] Vulnerability
- [ ] Exposure
- [ ] Governmetn Response

Then there will be a topsis code that calculates a risk score using all the above factor scores

- [ ] TOPSIS Risk Score

**Comment by d-saikrishna** [comment]
Risk Score Model documentation is complete

**Comment by d-saikrishna** [comment]
Shifted to #22
