### ISSUE TITLE
Run DRR pipeline for Odisha

### ISSUE THREAD

**Issue by d-saikrishna** [CivicDataLab/IDS-DRR-Data-Sources#21]
- [x] Decided to use subdistricts file for Odisha. Should find one.

| Source  | Variables | Status | updateFreq | Remarks |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| SENTINEL  | `NDVI`<br>`NDBI`  | Data Archived from 2019 to 2023 | Monthly | Unable to run Pipeline for 2018. GEE Error B11, B8 not available |
| GCN250  | `Surface runoff`  | Data Archived | Static | - |

Data Scoping reference:
1. https://ndmindia.mha.gov.in/images/pdf/Disaster%20Risk%20and%20Resiience%20in%20India.pdf
2. 
Update each source once the data is ready:

**Comment by d-saikrishna** [comment]
BHUVAN data source for Odisha is not good. Images downloaded are empty

**Comment by apoorv74** [comment]
@d-saikrishna - Highlight the BHUVAN related issue to the IDS-DRR project team
