### ISSUE TITLE
IDS-DRR | Curating data from all sources

### ISSUE THREAD

**Issue by d-saikrishna** [CivicDataLab/IDS-DRR-Data-Sources#8]
[Datasets Audit](https://docs.google.com/spreadsheets/d/1RRW5KZ1Csb3TPBgz_SZrtNSX3pT_W7upUE2wkHAoZOA/edit#gid=351886053)

Link to repo: [Sources](https://github.com/CivicDataLab/IDS-DRR-Data-Pipeline/tree/main/Sources)
`Wrote Script` --> `Data Reviewed` --> `Scripts Reviewed`  --> `Data Archived (2017-2023/08)` -->  `Pipeline Created`

| Source  | Variables | Status | updateFreq | Timeline |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| BHUVAN  | `Inundation percentage`<br>`Inundation intensity` | Data Archived | Monthly | July |
| SENTINEL  | `NDVI`<br>`NDBI`  | Data Archived | Monthly | July |
| TENDERS #10 @shreyaagrawal0809   | Count, Sum  | Data Archived* | Monthly | August |
| NASADEM   | `Elevation` <br> `Slope`  | Data Archived | One-Time | August |
| IMD #11 @tauseefsshah    | `Rainfall`  | Data Archived* | Monthly | August-->September |
| GCN250  | `Surface runoff`  | Data Archived | One-Time | September |
| BHARAT MAPS    | `Health Centres per RC` <br> `Road length per RC` <br> `Rail length per RC` | Data Archived | One-Time | September |
| WORLDPOP   | `Population counts` <br> `Sex Ratio` <br> `Aged Population` <br> `Young Population` | Data Archived | Annual | October |
| Mission Antyodaya 2020 #15  @tauseefsshah    | `net_sown_area_hac` <br> `avg_domestic_electricity` <br> `avg_telephone` <br> `pct_piped_water` <br> `pct_no_sanitary_latrines`| Data Archived | One-Time | October |
| FRIMS #7   | `All damages variables` | - | - | Waiting for API from Velocity |
| NERDRR  | `Proximity to embankment`  | Data Archived | One-Time | September |
| WRIS   | `Distance from rivers` <br>  `Drainage density` | - | - | October |

**Comment by apoorv74** [comment]
@d-saikrishna - we need a plan for all data sources. will it be possible to add all the data sources here and assign timelines ?

**Comment by d-saikrishna** [comment]
I'll do that. @apoorv74

**Comment by d-saikrishna** [comment]
@apoorv74 Please check. I've added all sources that are part of the model so far. We might add new sources as we progress.

**Comment by d-saikrishna** [comment]
Updates - added to the table
1. All sources except Mission Antyodaya completed

**Comment by d-saikrishna** [comment]
Mission Antyodaya 2020 completed

**Comment by d-saikrishna** [comment]
Should explore if a new source is needed for rainfall?
https://indiawris.gov.in/wris/#/

**Comment by d-saikrishna** [comment]
Update after the MVP Presentation:
1. New datasets were discussed for rainfall, 
2. ASDMA shared the revenue circle API - but it is an image layer. We asked for the vector layer. ASDMA has reservations in sharing that. We suggested that as per the new Geospatial policy, they can share vector layers.
3. SEC MoM data was discussed again but without any clear actionable.
